rows: 5
title: '&8Скупщик'
lore: '&9Цены: \n &f Цена единицы: {0}\n Цена 1 стака: {1}\n&9Действия:\n &9ЛКМ &f- продать 1 предмет\n &9ШИФТ+ЛКМ &f- продать 1 стак'
time: 1440 #в минутах
constantmenu:
  blue:
    id: blue_stained_glass_pane
    name: ''
    lore: ''
    slots:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
  Gray:
    id: gray_stained_glass_pane
    name: ''
    lore: ''
    slots:
      - 9
      - 8
      - 10
      - 17
      - 36
      - 37
      - 38
      - 42
      - 43
      - 44
  sellall:
    id: chest
    name: '&l&8Продать все'
    lore: 'Продайте все здесь'
    slots:
      - 39
  info:
    id: compass
    name: '&8Информация'
    lore: '&8Продавайте и покупайте предметы используя скупщика'
    slots:
      - 41
sell:
  period1:
    items:
      item0:
        id: cobblestone
        startprice: 200
        coefficient: 0.98
        period: 5
        slot: 0
      item1:
        id: diamond_chestplate
        startprice: 100
        coefficient: 0.95
        period: 20
        slot: 1
      item2:
        id: apple
        startprice: 100
        coefficient: 0.90
        period: 10
        slot: 2
      item3:
        id: stone
        startprice: 500
        coefficient: 0.75
        period: 15
        slot: 3
  period2:
    items:
      item0:
        id: apple
        startprice: 200
        coefficient: 0.98
        period: 5
        slot: 0
      item1:
        id: diamond_chestplate
        startprice: 100
        coefficient: 0.95
        period: 20
        slot: 1
      item2:
        id: cobblestone
        startprice: 100
        coefficient: 0.90
        period: 10
        slot: 2
      item3:
        id: stone
        startprice: 500
        coefficient: 0.75
        period: 15
        slot: 3
  period3:
    items:
      item0:
        id: cobblestone
        startprice: 200
        coefficient: 0.98
        period: 5
        slot: 0
      item1:
        id: apple
        startprice: 100
        coefficient: 0.95
        period: 20
        slot: 1
      item2:
        id: diamond_chestplate
        startprice: 100
        coefficient: 0.90
        period: 10
        slot: 2
      item3:
        id: stone
        startprice: 500
        coefficient: 0.75
        period: 15
        slot: 3